# Generated by Django 5.1.5 on 2025-04-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessquote',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
