# Generated by Django 5.2.1 on 2025-07-19 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='clinic_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
