# Generated by Django 5.2.1 on 2025-07-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointments_clinic_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WearableData',
        ),
    ]
