# Generated by Django 5.2.1 on 2025-07-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_healthmetric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthMetric',
        ),
    ]
