# Generated by Django 5.2.1 on 2025-07-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_healthmetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthmetric',
            old_name='sleep_seconds',
            new_name='sleep_duration',
        ),
    ]
