# Generated by Django 5.2.1 on 2025-07-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_sleep_seconds_healthmetric_sleep_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
