# Generated by Django 5.2.1 on 2025-08-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegan', 'Vegan')], max_length=20),
        ),
    ]
